language: java

before_install:
  - git submodule update --init --recursive
  - sudo apt-get update >/dev/null
  - sudo apt-get -q install cmake libcppunit-dev valgrind
install:
  - TERM=dumb gradle tasks
script:
  - TERM=dumb gradle hive --debug
